### ISSUE TITLE
貌似使用不了，出现未连接互联网错误

### ISSUE THREAD

**Issue by ktlsl** [PikachuHy/shadowsocks-client#1]

**Comment by PikachuHy** [comment]
你好 那个你的ss账号是可用的吗？
我这个是必须自己要有账号的

**Comment by ktlsl** [comment]
我有自己的ss账号的，使用qt5那个能够正常使用，是时候增加一个日志功能了，还有你这个客户端使用全局代理或者自动代理都会出现未连接互联网这个问题

**Comment by PikachuHy** [comment]
我现在把日志写到文件中，你再下载一下试试

**Comment by PikachuHy** [comment]
我刚刚提交了　你可以编译一下　我没有打deb包　这个日志还没有做完　
右键菜单－>帮助－>显示日志　可以看到日志
日志文件的保存在 ~/.ss/log

**Comment by ktlsl** [comment]
我找到问题了，不知道什么原因，我选择的aes-128-cfb加密方法没有写到配置文件里面去，我自己手动编辑那个gui-config.json 文件添加上去了就能够正常使用了

**Comment by PikachuHy** [comment]
好的　我马上查一下这个问题　
谢谢你的反馈
