### ISSUE TITLE
该适配deepin重构的dtk了

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#10]
已没法通过编译

**Comment by PikachuHy** [comment]
我还是用的15.4.1的dtk，deepin改了dtk的架构，但是还没放出来，我目前没有办法使用最新的dtk

**Comment by 1377195627** [comment]
arch这边已经推送了，deepin正式推送应该快了，但是deepin应该能自己装，你的源码中包含重构后的dtk中不存在的头文件，所有我直接换pkgconfig的dbase名为dtkcore会有头文件不存在问题，而那个头文件完全没必要导入。我的项目直接换模块名就直接能用了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
deepin这边肯定要等到15.5

**Comment by 1377195627** [comment]
不一定，今天arch这dde大换血，滚完之后虽然dtk还在，但是这货已经报废了。你尝试把dwidget_g....那个头文件去掉看看，这头文件真没用，再重构前，这货头文件已经被别的头文件包含过了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
等deepin推送了我再适配

**Comment by 1377195627** [comment]
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -11,7 +11,7 @@
 pkg_check_modules(3rd_lib REQUIRED
         QtShadowsocks
         botan-1.10
-        dtkbase dtkwidget dframeworkdbus
+        dtkcore dtkwidget dframeworkdbus
         libqrencode zbar
         )
 
diff --git a/src/common/dtk.h b/src/common/dtk.h
--- a/src/common/dtk.h
+++ b/src/common/dtk.h
@@ -14,5 +14,9 @@
 #include <dthememanager.h>
 #include <DWindowManagerHelper>
 DWIDGET_USE_NAMESPACE
+#ifdef DCORE_NAMESPACE
+DCORE_USE_NAMESPACE
+#else
 DUTIL_USE_NAMESPACE
+#endif
 #endif //SS_CLIENT_DTK_H
diff --git a/src/main.cpp b/src/main.cpp
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -18,8 +18,8 @@
         app.setTheme("light");
         app.loadTranslator();
         app.setQuitOnLastWindowClosed(false);
-        Dtk::Util::DLogManager::registerConsoleAppender();
-        Dtk::Util::DLogManager::registerFileAppender();
+        DLogManager::registerConsoleAppender();
+        DLogManager::registerFileAppender();
 
         MainWindow mainWindow;
 //        mainWindow.show();
diff --git a/src/MainWindow.cpp b/src/MainWindow.cpp
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -138,7 +138,7 @@
     connect(logService, &LogService::requestUpdateIcon, [=](const QIcon &icon) {
         systemTrayIcon.setIcon(icon);
     });
-    connect(updateService, &UpdateService::finishUpdate, &systemTrayIcon, &QSystemTrayIcon::showMessage);
+    //connect(updateService, &UpdateService::finishUpdate, &systemTrayIcon, &QSystemTrayIcon::showMessage);
     connect(pacService, &PacService::requestRestartProxy, [=]() {
         proxyService->setProxyEnabled(true);
     });
diff --git a/src/util/UpdateChecker.cpp b/src/util/UpdateChecker.cpp
--- a/src/util/UpdateChecker.cpp
+++ b/src/util/UpdateChecker.cpp
@@ -5,8 +5,6 @@
 #include <QtCore/QFile>
 #include <QtCore/QJsonDocument>
 #include <QtWidgets/QMessageBox>
-#include <dwidget_global.h>
-#include <dutil_global.h>
 #include <DDesktopServices>
 #include <model/JsonObjectSerializable.h>
 #include "UpdateChecker.h"
@@ -14,8 +12,11 @@
 #include "util/Util.h"
 
 DWIDGET_USE_NAMESPACE
+#ifdef DCORE_NAMESPACE
+DCORE_USE_NAMESPACE
+#else
 DUTIL_USE_NAMESPACE
-
+#endif
 /**
  * GitHub的附件信息
  */
diff --git a/src/widget/ShowLogWidget.cpp b/src/widget/ShowLogWidget.cpp
--- a/src/widget/ShowLogWidget.cpp
+++ b/src/widget/ShowLogWidget.cpp
@@ -5,7 +5,7 @@
 #include <QtCore/QDir>
 #include <QtWidgets/QVBoxLayout>
 #include "ShowLogWidget.h"
-#include <dutility.h>
+#include <DWidgetUtil>
 #include <util/Util.h>
 
 ShowLogWidget::ShowLogWidget(QWidget *parent) : QWidget(parent) {
@@ -22,5 +22,5 @@
     auto *mainLayout = new QVBoxLayout();
     mainLayout->addWidget(plainTextEdit);
     setLayout(mainLayout);
-    DUtility::moveToCenter(this);
+    Dtk::Widget::moveToCenter(this);
 }
diff --git a/src/widget/ShowLogWidget.h b/src/widget/ShowLogWidget.h
--- a/src/widget/ShowLogWidget.h
+++ b/src/widget/ShowLogWidget.h
@@ -8,11 +8,7 @@
 
 #include <QtWidgets/QPlainTextEdit>
 #include <QDebug>
-#include <dwidget_global.h>
-#include <dutil_global.h>
 
-DWIDGET_USE_NAMESPACE
-        DUTIL_USE_NAMESPACE
 class ShowLogWidget: public QWidget {
 public:
     ShowLogWidget(QWidget *parent= nullptr);










给你适配好了新版dtk，部分同时兼容旧版，其中MainWindow.cpp中的
connect(updateService, &UpdateService::finishUpdate, &systemTrayIcon, &QSystemTrayIcon::showMessage);

QSystemTrayIcon::showMessage貌似有重载方法，由于全程gedit修改，自己解决去，反正我不喜欢内置更新机制，还是包管理器好用，而且ss服务器保存不是保存到home下的？我tm卸了服务器全没了

**Comment by PikachuHy** [comment]
thanks, thanks.不过你那个代码能不能用md语法包起来，像这样
```
#include <QtWidgets/QPlainTextEdit>
```
你现在的代码我很难读啊

**Comment by 1377195627** [comment]
@PikachuHy 我去，你没用过diff？这是patch补丁，你直接用patch命令自动打上去了，复制粘贴到一个文件就好了，本来我是想直接上传文件的，然后发现不能直接发，然后就直接复制粘贴算了，懒

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
那个ss服务器的问题，我改成ss-qt5的模型后，它保存在`~/.config/shadowsocks-client/config.ini`

**Comment by 1377195627** [comment]
原来在哪

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
在`~/.ss/gui-config.json`
如果我没记错的话，以前的保存方法我是没有注释的，现在应该还有吧
我后面再加一个导出到json文件的action

**Comment by PikachuHy** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1080
这个正向代理　你熟吗？

**Comment by 1377195627** [comment]
正向代理？没研究过，不如去研究下路由器上的怎么自动代理的。pac自动代码不够完美，老把我域名给代理了（其中一个重定向到码云），然后就挂了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
pac可以自己设置哪些域名走代理的，可以编写那个用户规则文件，然后重新更新pac文件

**Comment by 1377195627** [comment]
懒，而且你这货bug不是一般的多啊

**Comment by PikachuHy** [comment]
有这么严重？我用的时候没什么问题啊

**Comment by 1377195627** [comment]
@PikachuHy 最新版，打造补丁编译安装启动，我去折腾了好一会，代理和ss连接终于正常了。不对你报希望了。我还是想办法解决newifi2这坑爹路由器用第三方固件2.4g断流严重的问题把。解决了直接上路由器ss就舒服多了，你的每次开机基本要退出重开。烦

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by 1377195627** [comment]
@PikachuHy 最新版，打造补丁编译安装启动，我去折腾了好一会，代理和ss连接终于正常了。不对你报希望了。我还是想办法解决newifi2这坑爹路由器用第三方固件2.4g断流严重的问题把。解决了直接上路由器ss就舒服多了，你的每次开机基本要退出重开。烦

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
怪我喽

**Comment by 1377195627** [comment]
终于搞定kcp+ss了，用上kcp真舒服，你什么时候才吧kcp功能加上啊，反正基础功能你又不去写完

**Comment by PikachuHy** [comment]
你现在延迟多少？用了这个后
我新版本是可以测延迟的

**Comment by 1377195627** [comment]
测试延迟没啥用啊，能看当前ss的流量使用情况，上下行网速才有用，这连安卓版ss都能做到，而且kcp都不知道？主要用来加速ss的，也可以单独使用，反正kcp+ss一般速度更快就是了，kcp是个好东西，怎么能不支持

**Comment by PikachuHy** [comment]
那这个上下行网速你用了之后有多少提升？明显吗？

**Comment by 1377195627** [comment]
我又没测试我怎么知道，以前k2带不动kcp，没用，现在家里的newifi2也带不动那就说不过去了，开kcp死活用不了，就成功了那么一次。之后又刷了几个固件，顶多开个ss

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
。。。。。
那你把整合后的代码发出来

**Comment by 1377195627** [comment]
，，，，
不干，自己调用gost实现，go写的，arch源里有

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
我已经适配了dtk2
