### ISSUE TITLE
能否支持shadowsocksr？

### ISSUE THREAD

**Issue by redapple0204** [PikachuHy/shadowsocks-client#11]

**Comment by PikachuHy** [comment]
我不熟ssr，你有没有ssr的资料

**Comment by redapple0204** [comment]
@PikachuHy https://github.com/shadowsocksr-rm/

**Comment by PikachuHy** [comment]
没有c++版的，得要看源码实现，这个就比较难受了。
要弄的话，会比较久，有他的一些源码解析的文章和与ss源码对比的文章吗？

**Comment by redapple0204** [comment]
@PikachuHy 或许....你看看这个？
https://github.com/shadowsocksrr/shadowsocksr-libev
https://github.com/shadowsocksrr/shadowsocks-rss/blob/master/ssr.md

**Comment by redapple0204** [comment]
还有这个
https://github.com/shadowsocksrr/shadowsocks-rss

**Comment by PikachuHy** [comment]
这个我看一下，底层我还需要学习一下。
如果你比较急用的话，记得时常来催我。
还有，就是文章啊，博客啊，别的大佬写的分析啊，都可以扔我这里，我不嫌资料多的。

**Comment by redapple0204** [comment]
@PikachuHy 好的，谢谢了

**Comment by PikachuHy** [comment]
社区给了一个cli，你可以去试试
