### ISSUE TITLE
关于网络代理的一个问题

### ISSUE THREAD

**Issue by Mut1** [PikachuHy/shadowsocks-client#12]
我在应用商店下载的ss-qt5。我跟着评论的做法配置好pac代理了；
我使用这个需要将之前自动代理的删除吗？

**Comment by PikachuHy** [comment]
你好 我之前的做法是配好控制中心=》网络=》自动下面的pac url地址，如果不行，再配好手动的socks代理，如果可以，再切换到自动。
话说你如果用deepin的话，直接用我的ss-client的就好了。都会自动帮你配好的。
