### ISSUE TITLE
问个问题/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by Mut1** [PikachuHy/shadowsocks-client#15]
我最近来学校后，连上校园网后。使用ss翻墙，可以访问YouTube，但是不可以访问gmail 等部分网站。请问是为什么啊?是校园网的问题吗？
你的软件我最近打不开了，也不知道是什么原因。难受啊

**Comment by PikachuHy** [comment]
请问 你是局部代理 还是全局代理 ？全局代理也上不来gmail吗？

**Comment by Mut1** [comment]
对对对。全局也不能访问。是校园网的原因吗？校园网是移动的20M速度。还有老哥你的软件我打不开了，不知道是为什么，所以现在用的你的在线的pac协议，然后用的ss-qt5连接的。

**Comment by PikachuHy** [comment]
哪个省的校园网 校园网客户端是哪个？

**Comment by Mut1** [comment]
江苏的。移动的校园网。客户端是什么意思？cmcc吗

**Comment by PikachuHy** [comment]
有的地方 校园网登录有个客户端 也可以网页登录 我不知道你那里什么情况

**Comment by Mut1** [comment]
ppoe设置 。然后填一个账户 密码。估计是校园网太慢了，你的客户端打不开是为什么 ㄒoㄒ

**Comment by PikachuHy** [comment]
你把日志发出来

**Comment by Mut1** [comment]
请问我手机开热点 为啥比宽带连接访问 网站速度快。但是我用测速软件 网速宽带碾压热点。。萌新不懂网络这东西，大神知道什么原因吗


2017-08-31 21:37 GMT+08:00 大黄老鼠 <notifications@github.com>:

**Comment by PikachuHy** [comment]
这个我不是很懂耶

**Comment by PikachuHy** [comment]
我打包了新的版本，你可以试一试，看能不能解决你的问题
