### ISSUE TITLE
编译不通过，估计是国际化问题

### ISSUE THREAD

**Issue by kikyoulzg** [PikachuHy/shadowsocks-client#16]
cmake ..没有通过，显示如下：
[~/shadow socks-client-master/build]
kikyoulzg-> cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

process translations/shadow socks-client.ts
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory

process translations/shadow socks-client_zh_CN.ts
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/kikyoulzg/shadow socks-client-master/build/CMakeFiles/CMakeOutput.log".

**Comment by sunnyyuu** [comment]
我遇到了同样的问题，通过安装以下包解决了，但是cmake有3个国际化失败，make -j4的时候找不到dwiget global.h之类的，只好放弃了，直接下载deb包安装啦。
sudo apt-get install qttools5-dev-tools

**Comment by PikachuHy** [comment]
你好 感谢你们的反馈 
目前我遇到的情况是 deepin升级dtk后 
我自己也编译不过了 我会尽快解决升级后的适配问题的

**Comment by PikachuHy** [comment]
问题已经解决了 我也写了一个一键编译的脚本
