### ISSUE TITLE
【保护本地PAC文件】的勾打不上

### ISSUE THREAD

**Issue by sunnyyuu** [PikachuHy/shadowsocks-client#18]
【保护本地PAC文件】的勾打不上。
系统版本：Deepin 15.4.1
软件版本：shadowsocks-client_1.0.0-1_amd64.deb

**Comment by PikachuHy** [comment]
这个是我的问题，我没大懂ss-win上的这个按钮干嘛的？
后面就废弃了，如果这个没什么用，我下个版本就把它去掉

**Comment by PikachuHy** [comment]
我把它去掉了，等以后这个Action语义明确后我再加上
