### ISSUE TITLE
cmake install规则中的图标你怼错地方了

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#2]
图标存放路径应该是/usr/share/icons/hicolor/xxxx下

**Comment by PikachuHy** [comment]
原来是放在这里的呀　怪不得呢

**Comment by PikachuHy** [comment]
我已经改了　把图标文件放在`/usr/share/icons/hicolor/128x128/apps`下
并且修改了.desktop文件
谢谢啦

**Comment by 1377195627** [comment]
kcp会集成进去不

**Comment by PikachuHy** [comment]
暂时不会吧 现在要先赶上win版的进度 如果win版已经做了 那就做 没有的话 等win版上的功能基本都完成了 再添加这些功能

**Comment by 1377195627** [comment]
我已经打包成alpm包了
[0.3.1](https://git.oschina.net/flyos/flyos-mirrors/raw/master/x86_64/shadowsocks-client-0.3.1-1-x86_64.pkg.tar.xz)

**Comment by PikachuHy** [comment]
alpm包是什么？

**Comment by 1377195627** [comment]
arch等pacman管理器用的包，，，

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by wjkcs** [comment]
发送到桌面上的时候图标路径还是没改

**Comment by PikachuHy** [comment]
哪个图标路径？我现在的路径是`Icon=shadowsocks-client.png`

**Comment by wjkcs** [comment]
发送到桌面上的话会不显示图标，手动把路径改成Icon=/usr/share/icons/hicolor/128x128/apps/shadowsocks-client.png就好了

**Comment by PikachuHy** [comment]
我也感觉是的　我很多JB的图标显示不正常
