### ISSUE TITLE
可以关闭但是无法开启

### ISSUE THREAD

**Issue by smallsat** [PikachuHy/shadowsocks-client#22]
在任务栏右键图标，可以正常关闭代理，但是无法再通过图标打开代理，只能到设置里手动打开

**Comment by PikachuHy** [comment]
能说得更详细一些吗？我记得第一个action就是启动代理啊

**Comment by smallsat** [comment]
我在使用的过程中，临时关闭ss 可以正常关闭（没有退出，只是取消勾选系统代理），等我再次勾选系统代理的时候，在deepin中的设置中心中，代理还是关闭状态。

**Comment by PikachuHy** [comment]
这个呀 我和深度控制中心使用的是同一套api，都是深度自己做的，我也不知道为什么无法同步更新。但是，这个不影响使用吧！
