### ISSUE TITLE
编译老问题

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#23]
![image](https://user-images.githubusercontent.com/8142265/30679755-40974130-9e61-11e7-9481-070ba9a22186.png)
能不能解决下这问题啊，永远的报错，反正我不想看你代码，太乱

**Comment by PikachuHy** [comment]
哎哟 我不是写了release脚本吗？

**Comment by 1377195627** [comment]
有屁用，你这也太局限于debian了，而且我是正常的cmake然后make，而且生成qm文件完全可以用cmake直接生成，不需要写脚本再调用

`file(GLOB INSTALLER_TRANSLATION_TS
        ${CMAKE_CURRENT_SOURCE_DIR}/translations/*.ts)
set_source_files_properties(${INSTALLER_TRANSLATION_TS}
        PROPERTIES OUTPUT_LOCATION ${CMAKE_CURRENT_BINARY_DIR}/translations)
qt5_add_translation(INSTALLER_TRANSLATION_QM ${INSTALLER_TRANSLATION_TS})
add_custom_target(installer-qm-update DEPENDS ${INSTALLER_TRANSLATION_QM})`

**Comment by 1377195627** [comment]
不，目测官方的只是方便测试而已，qmake/cmake/make过程并没有去调用，而且深度的开发者好像并没强制所有人必须用qtcreator

**Comment by PikachuHy** [comment]
哎呀 我就是抄的他们的cmake配置 用clion写的

**Comment by 1377195627** [comment]
我给你的那段是参考deepin的安装器里的cmakelist上的
