### ISSUE TITLE
软件更新建议

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#24]
将核心功能抽出来写成共享库，大更新更新整个软件，否则只更新共享库，同时更新的共享库放主目录下，还不用管权限问题

**Comment by PikachuHy** [comment]
这个等我忙过这阵子再实现吧

**Comment by 1377195627** [comment]
还有，强烈建议加入插件机制，方便第三方扩展，你现在的功能太少了，说真的，你的还没ss-qt5好用.....甚至连查看ss连接状态都很麻烦

**Comment by PikachuHy** [comment]
我当初设计的时候，就只是想简单的完成局部代理和全局代理的切换。没考虑这么多。

**Comment by PikachuHy** [comment]
你所说的ss连接状态是个啥？

**Comment by 1377195627** [comment]
查看ss的连接状态啊，比如你连接一个ss服务器后，谷歌之类的打不开，难道你就不需要去检查ss连接是否成功？你的软件只能通过看日志确定，而且不好确定是服务器问题还是客户端连接问题，你用过路由器上的koolss或者ssr插件没，那上面不仅可以ping服务器还能连接后检查是否连接成功
![deepin-screenshot lh8042](https://user-images.githubusercontent.com/8142265/30700700-f6968594-9ead-11e7-865b-cde151d73235.png)
![deepin-screenshot tj8029](https://user-images.githubusercontent.com/8142265/30700699-f685522e-9ead-11e7-8311-6dddb3872cac.png)
毕竟服务器是别人自搭建的又不是自己的，服务器有时候暂时挂了也很正常

**Comment by 1377195627** [comment]
关于那个系统代理，建议参考路由器的做法，
![image](https://user-images.githubusercontent.com/8142265/30700847-5e8b05da-9eae-11e7-9af7-fc61cbc77739.png)
效果更好，系统代理并不能解决dns污染问题吧

**Comment by PikachuHy** [comment]
没用过koolss和ssr

**Comment by PikachuHy** [comment]
你这信息量有点大啊 我还不知道怎么解决

**Comment by PikachuHy** [comment]
还有 ss-win也没这些功能啊

**Comment by 1377195627** [comment]
本来挺看好你这个项目的，毕竟我也想写个，然后看你出了，就懒得自己写了，自己挖了一堆坑还没填完......然后过了这么久........你还没完成，还好我平时都是用的路由器ss

**Comment by 1377195627** [comment]
ss-win没怎么用过，不知道，但是路由器上的koolss挺强大的，不知道有没有开源，没找到源码

**Comment by PikachuHy** [comment]
那你自己基于ss-qt5写一个吧 反正你懂得比我多 
我现在重点不在这里 我只要求ss-client在deepin能稳定运行 
满足我自身以及有ss-win使用习惯的人在deepin上方便上网 
而且 你说的很多词我都没懂 至少目前不知道是什么意思

**Comment by PikachuHy** [comment]
我对你那个路由器上的挺感兴趣的 毕竟我有不少设备需要用 每一个都搞一个ss的客户端比较麻烦

**Comment by PikachuHy** [comment]
况且 我最开始的目的是为了dropbox能正常使用 但是 不管我用什么方法 在ss-qt5的基础上 怎么弄都没有效果 dropbox上网只能借助于proxychains 
另一方面 deepin的文管对于dropbox的同步 做得不如win 我使用的时候觉得不是很好
再者 我不是很理解你的需求 感觉上 我们对ss的使用不在一个层次上 
我做的ss-client只是为了在deepin上上网的习惯同win，并不需要你说的那些，能上google，能看Youtobe，就行了，可惜最主要的一个功能没有完成
