### ISSUE TITLE
普通用户下突然无法启动，终端中运行提示“段错误”

### ISSUE THREAD

**Issue by wjkcs** [PikachuHy/shadowsocks-client#25]
![deepinscreenshot_select-area_20170921225216](https://user-images.githubusercontent.com/26520783/30702872-b65e0b00-9f20-11e7-84d2-2455efef5c5c.png)

**Comment by PikachuHy** [comment]
你有更新libss的库吗？ 直接图标启动有问题没有

**Comment by wjkcs** [comment]
直接启动没反应，终端下用sudo shadowsocks-client 命令才能正常启动

**Comment by PikachuHy** [comment]
这是什么情况？ 是按照的最新版的吗？有没有自己额外按照ss

**Comment by wjkcs** [comment]
最新版，没用其他ss，有一点很奇怪，用sudo shadowsocks-client启动后，默认勾选了开机启动，取消时会报错，是不是开机启动有bug？

**Comment by PikachuHy** [comment]
你解决了？

**Comment by wjkcs** [comment]
没，我决定重装遍系统

**Comment by PikachuHy** [comment]
。。。。。。。。。。。。。。
