### ISSUE TITLE
Deppin 15.5beta 点击启动系统代理就崩溃了

### ISSUE THREAD

**Issue by Dimon94** [PikachuHy/shadowsocks-client#28]

**Comment by PikachuHy** [comment]
我的Deepin 15.5 Beta系统崩溃了。。。。。。。。。。。。。。。
5555555555555555

**Comment by Dimon94** [comment]
这么尴尬的咩？我的系统没事。。。就是字体变丑了

**Comment by PikachuHy** [comment]
我安装15.5 Beta后 系统提示我升级 然后我升级  系统就崩了。。。。。
这个小东西我的确该更新了 我自己现在的SS账号都没有办法使用

**Comment by Dimon94** [comment]
期待更新，以前我都是用电脑lantern，手机SSR，最近lantern都不是很稳，deepin这没挖掘到很好的fq工具，才挖到你这个项目的！
可惜不会修这个崩溃bug，不然就自己修修了。

**Comment by PikachuHy** [comment]
我这个是基于qt5那个改的，底层的库都一样，就界面不一样，然后我加了一些我自己常用的东西

**Comment by wjkcs** [comment]
我这里还能用诶，也是15.5beta

**Comment by PikachuHy** [comment]
现在绝对没问题的
