### ISSUE TITLE
小提议，希望客户端退出（主动退出）后能够还原代理（设置无）的设置

### ISSUE THREAD

**Issue by ktlsl** [PikachuHy/shadowsocks-client#3]
要不然又要去代理哪里自己去设置回去，挺麻烦的

**Comment by PikachuHy** [comment]
好的

**Comment by PikachuHy** [comment]
我已经修改了，并且重新打包
[新的Release](https://github.com/PikachuHy/shadowsocks-client/releases/tag/v0.3.%EF%BC%92)
谢谢你的反馈
