### ISSUE TITLE
v1.1.0-alpha之后的deb安装后都用不了

### ISSUE THREAD

**Issue by yuansushow** [PikachuHy/shadowsocks-client#38]
v1.1.0-alpha可用。但是之后两个版本都用不了。
图标打开没反应，在命令行下运行显示找不到libQtShadowsocks.so.2

**Comment by redchenjs** [comment]
@yuansushow 应该是libqtshadowsocks没有静态编译进去，又没写libqtshadowsocks的依赖，你自行安装一下libqtshadowsocks就好了

**Comment by licardoY** [comment]
` shadowsocks-client 

shadowsocks-client: error while loading shared libraries: libQtShadowsocks.so.2: cannot open shared object file: No such file or directory
`

**Comment by PikachuHy** [comment]
看来我还是把依赖打包进去比较好

**Comment by PikachuHy** [comment]
你的问题用v1.2.0应该可以解决了
