### ISSUE TITLE
启动时不会启动ss bug

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#4]
启动时不会启动ss，每次都要自己点服务器切换下服务器才行，烦，而且托盘的图标太丑，还没原来的好看，还有开机自启功能的实现方法:直接吧desktop文件复制一份到.config/autostart下即可

**Comment by PikachuHy** [comment]
这样还不行，虽然能自启动，但是与deepin的样式有些不同，我还要再问问

**Comment by PikachuHy** [comment]
不知怎么好像又能同时反应了
