### ISSUE TITLE
状态栏图标2k屏不清晰

### ISSUE THREAD

**Issue by licardoY** [PikachuHy/shadowsocks-client#40]
可不可以支持下高分屏.

**Comment by PikachuHy** [comment]
很抱歉，我邮箱把GitHub的这个邮件放到垃圾箱了。
请问，你能不能给我个截图
因为我的屏幕是1080的，我还不知道2k屏的效果是怎么样的。
谢谢

**Comment by licardoY** [comment]
之前是老版本,不知道是不是显示问题,更新了最新版后很清晰了,谢谢
