### ISSUE TITLE
扫描屏幕二维码功能还有问题

### ISSUE THREAD

**Issue by wjkcs** [PikachuHy/shadowsocks-client#5]
二维码扫描无效，提示没有找到包含有效ss uri的二维码

**Comment by PikachuHy** [comment]
稍等　我试一下

**Comment by PikachuHy** [comment]
![_ _20170806232900](https://user-images.githubusercontent.com/18223871/29004737-55f3411c-7aff-11e7-8254-869e6a4f6e5d.gif)
我能扫出来啊
你的二维码是正确的吗？

**Comment by wjkcs** [comment]
二维码应该没问题，windows和手机上都试过，你截图里的二维码我也试了下也是扫不到，我看日志里显示的是:扫描到二维码 "" ，好像是都没有扫到二维码，之前有用ss-qt5也是有这个问题

**Comment by 1377195627** [comment]
@wjkcs 可能跟你的环境有关，你看看你是不是少装了什么依赖，终端运行，然后扫二维码看看

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by PikachuHy** [comment]
不知道你的二维码里面有几个ss账号，目前只能解析一个，格式同官网的。
![_ _20170807194431](https://user-images.githubusercontent.com/18223871/29025353-e06b2f72-7ba8-11e7-87be-2e49b6155927.png)

**Comment by PikachuHy** [comment]
@wjkcs 我二维码扫描借(chao)鉴(le)ss-qt5的，所以扫描结果肯定是一样的　：）
