### ISSUE TITLE
启动时ss连接失败的bug啊

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#6]
![image](https://user-images.githubusercontent.com/8142265/29246464-437952a4-7fc0-11e7-9e26-0f4dff5af5a1.png)
怎么还不修复啊

**Comment by PikachuHy** [comment]
我看看

**Comment by PikachuHy** [comment]
我没有处理连接失败的情况，
看来我需要加点什么东西

**Comment by PikachuHy** [comment]
开始改了，还没有改完

**Comment by PikachuHy** [comment]
新版本已经打包了，可以去下载最新的版本，已经适配dtk2
