### ISSUE TITLE
开机自启导致启动器打不开

### ISSUE THREAD

**Issue by 1377195627** [PikachuHy/shadowsocks-client#7]
开机自启导致启动器打不开也就算了。服务器也没成功连上，必须重新打开再重新点服务器才能连接上

**Comment by PikachuHy** [comment]
这是什么问题。。。。

**Comment by 1377195627** [comment]
我才发现启动器打不开是因为你的客户端开机自启导致的，退出了就能打开了，而且开机自启可以参考下octopi的做法，这货不是扔.config/autostart实现的，https://github.com/aarnt/octopi

**Comment by PikachuHy** [comment]
ok 谢谢
我现在的一个问题是没有看懂deepin怎么实现的，它的那个代码我跑不起来

**Comment by PikachuHy** [comment]
已通过dde-api完成开机自启动

**Comment by 1377195627** [comment]
居然dde还有这东西？

**Comment by PikachuHy** [comment]
deepin做了很多底层的工作，使用go封装了一下，这个就是dde-api。
通过dbus给Ｑｔ提供接口

**Comment by 1377195627** [comment]
什么叫通过dbus给Ｑｔ提供接口，这叫用dbus导出接口

**Comment by PikachuHy** [comment]
可以参考老王的文章　http://www.jianshu.com/p/e871723f9460
这是我目前见到的最详细的deepin开发文档了
然后　请看这个项目　https://github.com/linuxdeepin/dbus-factory
这里面有go暴露出来的dbus接口
我一般是有需求，看deepin已有的项目完成了没有，如果有的话直接抄deepin的

**Comment by 1377195627** [comment]
然后就有个问题了，在非dde下就没法用了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by 1377195627** [comment]
那个api，好像还是直接怼到.config/autostart去啊。而且那个日志，时间久了，第一次打开慢的要死，改成异步加载多好

**Comment by 1377195627** [comment]
ss概率性没法启动的问题还是存在啊
